// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD79CAtOGgrtTdOgCFPcciQ6WHRmfNiHfk',
    appId: '1:1036477050422:web:b047c46a713a843e0af297',
    messagingSenderId: '1036477050422',
    projectId: 'todo-app-72def',
    authDomain: 'todo-app-72def.firebaseapp.com',
    storageBucket: 'todo-app-72def.firebasestorage.app',
    measurementId: 'G-HEL2X3D9NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdludGSbXyQTgy97AN-0H6BtJlPSSat30',
    appId: '1:1036477050422:android:3c7870b486405f600af297',
    messagingSenderId: '1036477050422',
    projectId: 'todo-app-72def',
    storageBucket: 'todo-app-72def.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMrx2us5ZfMw0lOV73ZtJ-GSjp-OM8xQg',
    appId: '1:1036477050422:ios:bbd54318b442fdb30af297',
    messagingSenderId: '1036477050422',
    projectId: 'todo-app-72def',
    storageBucket: 'todo-app-72def.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMrx2us5ZfMw0lOV73ZtJ-GSjp-OM8xQg',
    appId: '1:1036477050422:ios:bbd54318b442fdb30af297',
    messagingSenderId: '1036477050422',
    projectId: 'todo-app-72def',
    storageBucket: 'todo-app-72def.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD79CAtOGgrtTdOgCFPcciQ6WHRmfNiHfk',
    appId: '1:1036477050422:web:5e17208b60eb1f290af297',
    messagingSenderId: '1036477050422',
    projectId: 'todo-app-72def',
    authDomain: 'todo-app-72def.firebaseapp.com',
    storageBucket: 'todo-app-72def.firebasestorage.app',
    measurementId: 'G-CQ622Z0XS4',
  );
}
